---
- name: Prueba Registry
  hosts: all
  gather_facts: true
  tasks:
  - name: Ejecutar commando
    command: uptime
    register: salida_uptime
  - name: Mostrar comando
    debug: var=salida_uptime.stdout_lines
