---
- name: Tools Setup
  hosts: nginx-servers
  become: yes
  gather_facts: true
  tasks:
    - name: Vim and Net-Tools Installation
      yum:
        name: "{{ tools }}"
        state: latest
      when: ansible_distribution == "CentOS"
