---
- name: Docker Setup
  hosts: master
  become: yes
  gather_facts: true
  tasks:
    - name: Tools Installation
      yum:
        name: "{{ master_tools }}"
        state: present
      when: ansible_distribution == "CentOS"
    
    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      when: ansible_distribution == "CentOS"

    - name: Docker Installation
      yum:
        name: "{{ docker }}"
        state: latest
      when: ansible_distribution == "CentOS"
      notify: start_docker_service

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

  handlers:
    - name: start_docker_service
      service:
        name: docker
        state: started
        enabled: yes
